### ISSUE TITLE
Face Detection Issue

### ISSUE THREAD

**Issue by wannabegamedeveloper** [wannabegamedeveloper/Rubiks-Cube-Object-Detector#1]
Issue in handling face detection.

**Comment by generalkakru** [comment]
What is the issue exactly?

**Comment by wannabegamedeveloper** [comment]
Face detection is not working properly. I needed some help regarding that. Please look at my code.

`import cv2 as cv

def GrabVideo():
    return cv.VideoCapture(0)

capture = GrabVideo()

while True:
    isTrue, frame = capture.read()
    if (isTrue):
        gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
        faces_rect = haar_cascade.detectMultiScale(gray, scaleFactor = 1.1, minNeighbors = 3)

        for (x,y,w,h) in faces_rect:
            cv.rectangle(frame, (x,y), (x + w, y + h), (0, 255, 0), thickness=2)

        cv.imshow('Face Detection', frame)

        if cv.waitKey() & 0xFF == ord('d'):
            break
    else:
        capture = GrabVideo()

cv.waitKey(0)`

**Comment by generalkakru** [comment]
Kindly accept pull request.

**Comment by wannabegamedeveloper** [comment]
Saw your file. Works for me. Thank you.
